DROP TABLE IF EXISTS BRANDS;
DROP TABLE IF EXISTS PRICES;

CREATE TABLE BRANDS (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(20)
);

CREATE TABLE PRICES (
id INT AUTO_INCREMENT PRIMARY KEY,
brand_id INT,
start_date DATETIME,
end_date DATETIME,
price_list INT,
product_id INT,
product_name varchar(50),
priority INT,
price DOUBLE,
curr VARCHAR(3),
FOREIGN KEY (brand_id) REFERENCES BRANDS(id)
);